image:
  repo: ghcr.io/ukyi-app/page
  tag: sha-66839eb6ed8b9ab578a3af92acd3e8e6386f625d
  digest: sha256:0ede1c176aa97de244b408ce48cd6ca3056d747588184bf8444a9ae9967ba3aa
kind: web
replicas: 1
resources:
  requests:
    cpu: 50m
    memory: 96Mi
  limits:
    cpu: 300m
    memory: 256Mi
envFrom:
  - secretRef:
      name: page-secrets
  - secretRef:
      name: db-page-conn
route:
  host: page.ukyi.app
  paths:
    - /
  public: true
metrics:
  enabled: false
podAnnotations:
  checksum/secrets: b921000ca9977c25
