image:
  repo: ghcr.io/ukyi-app/page
  tag: sha-468dd508610b0f5eccaac84837036e01afa22d6c
  digest: sha256:3474c6a9e89a600be3b86affa9d56fbea04ec8fa1f4de1ec52a5aa85b0f54661
kind: web
replicas: 1
resources:
  requests:
    cpu: 50m
    memory: 96Mi
  limits:
    cpu: 300m
    memory: 256Mi
envFrom:
  - secretRef:
      name: page-secrets
  - secretRef:
      name: db-page-conn
route:
  host: page.ukyi.app
  paths:
    - /
  public: true
metrics:
  enabled: false
podAnnotations:
  checksum/secrets: b921000ca9977c25
