image:
  repo: ghcr.io/ukyi-app/page
  tag: sha-e0f16c719673120721a092a6c0c22229b2034f9c
  digest: sha256:20664916ffa3ef43d77046f3f4344040b491f39abc8e2ad9629996c5f50f4a29
kind: web
replicas: 1
resources:
  requests:
    cpu: 50m
    memory: 96Mi
  limits:
    cpu: 300m
    memory: 256Mi
envFrom:
  - secretRef:
      name: page-secrets
  - secretRef:
      name: db-page-conn
route:
  host: page.ukyi.app
  paths:
    - /
  public: true
metrics:
  enabled: false
podAnnotations:
  checksum/secrets: b921000ca9977c25
