---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    telegram-chat-id: AgBCNeMA3X3laBwXCx1aEqyBC3KFTFYFlvoUxLLOKB90xlmnVsP126m16hjMrxVU/7aivWm9YVTVTYdOqbk4CqeY5zXiZShcaib52WiJ4V8H7ncqL9oGbHBM0fYQpzljXcIs4deBeqJEhjs7k9eNc5M7BdXgWGFaXxonFjACpmvSLRlPxzePxpfVDOiOrnIgItGZI0pjAiYScxxYEMZod5XsMyD0NjZPPhhMpmEQsilh6OIVdxPH2ZCGEMtqu7V8sqYT6QkZwCf+3P6pYmcn4GQIOSDKOewwxSNzFg0n9wTGe3MQzSxLaUDR3j3pzFFYu725AoB3e5qX90zCjyB+qqmXtICTDxNuDS1EUrqjEUzlYOpcKAL7XKMs7ZEMHGPYuwP//B03bMEJsyUI35YEvKvMRg1sYsmrqUx6Sx8h8+qelNtQzxC3aM++Eg5m1XioUCK/otKJrrHhgP5fL9ZhpRc8ybQRxMqkSCErPwqPlFxmkQiEukB3eC3mQfyqicMqgSM+2IyECp7smoVWSQwz5cdBmM8NyufgYMnuuOrAirYkIIkOug56WZZGD2tp+WTMo3lYMkSouk4bt0pP6BygQ8nwV7TT56+vCr3daSaPhSQlG02Rgo1d+fLyiWWLRFPvZxfS7jXChdMC4uwi8oMK9rnZ9dYGQmZ0igXeui0wI8kk5WJvzzQQqGoe6yk2YRZlBlLMlLWAzspd1Uab
    telegram-token: AgB7TW3DMvCXhhdirx2334deeLrUcQac2julqW1LKwJ3GZxnVRWq5N6wBPdMod24tQ4aGvtCQd1Y3fnVxhFQk/972Vt3APp4C+Z/PNLZBhD/FzLmKU9RXEGhKB5ZtNlkTFAkblKYzKqSYWzjW81YQiA+5aGFWx9I2hXkXxvH4UKtokV+hiZ0di2ZSr8k0MG+THH2/xR6dA1g2kuJpFE1PoxJu7l6NcVLplYBo7LCIxb2mNJoVRvunSclB8hMtHbSB/sxg3lVLwLBG/Nh0LvwDyrV+qHPw++EU2HGbaSS6/NGeq2XrGB8o7Szt7s0OZ0xwXr6G51Nqm8M+6Wm5dCsXYXQz3Gy7C7J41KpsxuoqP09HY6RDwOQLgNhR7S4vIfbG/UAjzQ0l+PHhE1MnLaOrJpncnXe3itImZf4y2S3pwTK0/CLxYcXAmzF8EekKtHHJFZI4QSuEXyZ0D3hmsrOkPUmtts6/sxd6NPysk9STy+QqCLq8iQPkGWMNMx47Sd19Yb4y4OhsdEunzGdTMTTjEWNbFQnN72duyNMnwg2MVkwvmXt0xW1B6qeLUO0Jg3520TFI3UT9uEzLN1jB0ACMsXBFtN4LuLOyCaa1UWh19n+0OSSs1OT4Wfz7bpvcrGZIEvEgQg47VT+8CnwOZSDdU8e0hC/3dfRSjHfJdgQrG12ORwcsO7saLK3CHNZ1sGak3kwnIryjrkCew1Bf6qQ36EYSc4wUlogHnISFAlZF78AK41zNBsaNvbr3yDApvjN
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
