---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    accounts.ukkiee.password: AgBFfUCZbqk49weXgGZFOiuOj9HH9oqNIncxhy70U8ZvLzwV+ESIF29ISVpxmiBRs3IxQA8hSIGyl32VdteS0RKd6M0uwzQ3S8Y79EVcAfBIRvM5eHY3Sxv6yrK1Uc3HDm1FuvUmRZuJF5bUQZURlxnvekLIcWlj+1ndvZjnTXbOhiupQArR5Wbo5Dtg/hSN9h90Ygz4WAaU4FxqMbflFzvUt4fh4mfn/RMqlhd6IGhG6Xyk85wvTAxOesqXRyBEHTF7de1Z3GCOy+jv06jWGx9PSITGRZT9zYTXdvM43wkYavGbPDF/oYuckgaG9E3Ybyqj+OE9QWVhCebS/I/7YaVKgulez9IEAQ6x6cmfv4scKn+mLkMcznCYhKNNnoVNYKSNgMJFQardsOhymFCJS8PGGcqh54oPWjuQKOpWY0u54U2SfHF5IrGQ1HkFOKb4o10Xnr2sC9OsM66oBm/sweLchCrbN7JoT/Ro95nDxMFSDzvss1u5G737Zd5MnYnURmorAN9o9L75enXJCDWy+YPkpEbz0wAfwKA/dzbGNRScV9WBo9OI1kISE2obNHfoUQq0tD7oj/c27LDomXuQXNf4txbYTXmO8ZAd6tHYUkZl/Aee0muvx7eg5NOkRnWYIdswz+A7BSbph1UDs8f6IqvOUTTEZYzgVzkRzQ2jCIH/hturiGZJfxvLgN05Bl94P5hMzDmjgIuaDxYpTjxeT3KujTNIymTwenMRCmXz4T9LJz2mqJ6+s+HCv9W/qlVksl+OB/vT1J4D8j1KGho=
    webhook.github.secret: AgCmg0R0yLJ1OdRyRRcfZg01NS1dCDPyBL3z0UzNTFFPDnTEbu7j5G66eKdBczl8GlYwTskRG3gaRLKnJxnfTf7Ny+kCnQWtg5GjkWWx8sNhVjjZkIB5k9Re36/UPyQarTsN6ehrZNMJI5rdmTzGbR6753h29CTF4G5h8LdHXyQNTf3f9tXuSduCHdlSBEE0lSFT2dVYgu4I+lqzioc8YLb2WJ36GIGJ2O57ZKHpEHtruTzFftEeUQyCeC6QEukrUkVupNuvxlOj9iVici5Nfhqu4DG7+kaloiZ8lv+uBQPq6BI50RCyofMwaN87Azl41pJjjWSmL6R5+HWC8KW435GeNOQDUTS4UTVKwncn5rpdGsufl3fejP6uU7AGOlljU4JxDRH0Nju/fMhG5vycn4TFCErjfTA1xDei7M52g8vOP9VQULjRrw2z2CL6S9iofma6ZkTDsdoHjTCS4rWnMS20TbSvmN2ZtmCXZAqHaKVTT2PKKeHRS15URRySFfGu0FqL/lFU/WYkot1AqRmGC6KqnIMvcG5a6XZfpJtU3IHjSzFsyGaRBsBX/CtPfO2i85OwQJZh5i9LvcqKZnhV4fkh+m/UAi3imm+0DoP4+crUPIJ7cSWa5i2jyzKTIHsm4tca/prif+qpw7wF7ivyJnxsaEHr1Bgt/CEWCtnwMaHmHbScfmwEuK6Pbi+8IX6nQ5zrw2WH/VC1Y0mK74WdQ56b0+1L7qMGc70V5UswN20nvrthP1wbSioQAsB7GdCITahkSheoWTpWqy75kxsBz8fx
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/patch: "true"
      name: argocd-secret
      namespace: argocd
    type: Opaque
