---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    telegram-token: AgC2qvjNglwEvs3dX6HwG6wyEHYx5Be+1Q2vw3aEMA3/Ev563HAhjBZrie31Sv0Cyr9jCJInimrZ6RXcNqRkXi7ELTX+8RFrUMSYaXhROyj3dOEacdt613LDSKSZL8rmPHqfZUrc490Ca8Ezt9oPEfgqLUteMjSTpoctktrVDt1qfmJ5kCSKfYzSS/czUI8ZWVbap0y1PlE/lelxvA4SwX4NSOuz++diKnkqMdUDI84rmTaZB3TkDJ0DhgaOCQYXU4tNEt7j3mqbzPMz9I1v7Znh5eU86mMSvzvzSDe7tNWWVZfDChuAIoNPFyxlysAt+InKN4LbppqGs5GG4cgtlOQLYehqXk57sPI/ycKfVd0NIAOIPosibamB6tbbkxf/a46I4bXjx8cWrK3to+4YHkJlC4gMdMVEzJcBFSPwhVDP0EYQ9SnkzQ6xwDwSyVNcT/INNTX20V8Jzw63TkYXlO8xQDjWokwoWOzMIL7qHhauO6gUszJTDtTOzzEVjJGRN6iu/emMxjHELuUU5k2nXhtka+mv1RJAiOAs2j1DtmCVoR0WqY0Qv5g9UUcaRDmtEjhR3fLgDVfI+sUU7ZiRpaoNDCEE7pDa4TmCYHhEmtnk7m9A3hRlwjicwYG231BNIgM6BySdlznkrkecJz2C/Ypcr89bwBfNXkFCdFtOjI6SzW6bUaMDzX7ddaW123ljwBtJPT3di68fI0vhEXt+nvWSXGthSU5Fj5TJN+qip1VAp0fEvusl1pdih8mtrN4a
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
