---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    telegram-token: AgCECJKvRqJLDRknbgJV+tbO9FFN5R/fBcAqP5xWnUQfkIn0Ruljfptthwp7w0YjQKkCfFcCSG+fN04F7BdAegznVHnGRYv0O6E87ldWJWDbIHAilb6FgKDbfOKMc1BBAcneN36a2JOS3eD0vVhZdTfCXHVs3o8Tm5oTvkd9BE45g2ECZUvZOIZqDGhC55VlTyAFLN2oiahwuAsfpDrfS/BDzrTtnkRpvkh8YVSzSIXp6wkRCE2+o01aT3qdnGSCbMMCXNDAsTVMHkgk0wxxU/0+jNQVAFCm/uWvHaxia6Di8ZeA4NOYjHjZDgNWUsz4dQSx7IHPmaEzQaJehRFbZlGhosSiCPXFbmnVniw6HGjempWQinipOohrq2IkiVtXqct0+ue8RmQtSq24lfjSUOFndl6m0zOoXTcX3/w4ItqrbFv1+Emtax80DmYiKgtZDtKCPmo6xacqVR5MtuJoJnG/ZemB2+KRn3kzC41y+nXvU4T7t36TXi6ZIoNLyM89h62qVLD8FRAlkQjjc6IM1Jp3bzUijSgQiSLCmJq6lP+tE1Xz+pj2Ls74naR6DncHQFGf750v3rataPgbF7Cp19CaXniyULt8FvNMna2ZJLt4e260e+zbIBOBWiHYWlqjcCIQDUmKYE5HQI2KaJkGFN+0aTeN64uof2IfrLUFx3NJ1MVJCQEnvPmdDuxz8p7K9dPfOjkxlu22TTZNA1v9xds3PfEMoIy8mDbtKikYs8Yh3xEFiRKtwoG2HDXherzY
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
