apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: edge # adguard-prod Application의 권위 있는(authoritative) 대상 namespace
resources:
  - pvc.yaml
  - adguardhome.yaml
  - deployment.yaml
  - service.yaml
  - ts-ingress.yaml
