apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adguard-ui
  namespace: edge
  annotations: { argocd.argoproj.io/sync-wave: "-6" }
spec:
  ingressClassName: tailscale
  defaultBackend:
    service: { name: adguard-ui, port: { number: 80 } }
  tls:
    - hosts: ["adguard"] # adguard.<tailnet>.ts.net
