image:
  repo: ghcr.io/ukyi-app/aiops-autodeploy-canary
  tag: sha-200c47593580ae482d5add1a9bf04d1b6159a169
  digest: sha256:1f888b35c3e8c864c1c6d5320d30ca11e60b4a81113a4fa2fd8ae9c35bd666d3
kind: site
replicas: 1
resources:
  requests:
    cpu: 10m
    memory: 16Mi
  limits:
    cpu: 100m
    memory: 32Mi
route:
  host: aiops-autodeploy-canary.home.ukyi.app
  paths:
    - /
  public: false
static:
  server: sws
metrics:
  enabled: false
