image:
  repo: ghcr.io/ukyi-app/aiops-autodeploy-canary
  tag: sha-46c4f899c6b77df9675c5793be97a454922e9fc9
  digest: sha256:ac1a0997c26c55bd5488608fd8458b1884c4ce09a9b038d3601fd713ef1b5aa4
kind: site
replicas: 1
resources:
  requests:
    cpu: 10m
    memory: 16Mi
  limits:
    cpu: 100m
    memory: 32Mi
route:
  host: aiops-autodeploy-canary.home.ukyi.app
  paths:
    - /
  public: false
static:
  server: sws
metrics:
  enabled: false
