- Links:
    - GitHub:
        - abbr: GH
          icon: si-github
          href: https://github.com/ukkiee
    - Instagram:
        - abbr: IG
          icon: si-instagram
          href: https://instagram.com/ukyi_
