---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aiops-observation-auth
  namespace: database
spec:
  encryptedData:
    authorization: AgCxbP/3vdvLBsRbfyE2zqrCIwKCFZT9ccBRAT0ca4z2aE7e3z8S+pqnAtNYNYsX8SUMH+b+z/PvqSBYvCWrPwKfN3PwlEvXji/HopQd11o5tJX9omW8cfsre4VMgbkZBJFI26ZYZQdrkRx8bPYlqSUdbxbLoUS4chwIicQzvIoVtsN+pY3FUW9gWQFzYtziD2bVZuyvXJQG4H10VBaqxAPR07HF5jfadDilgUCWjetw8g0R9NUOM5se8RtDGBb3/1RplyoTPK+e6xVyQ6nOVPPmMvsHB2z6WD4fAtlEAeyy9gjaEHRMy2rs71vfAI2NFefQYvFzYGQBR3mTalofZelUaNk2N3pVQ8mRwFRyvAWrhjb+LzuQAIaP/Xp/ha0FmYWvL35nOjH0Yzd0hIbsnEiAfeZkIgBKYt52Ze3XUp5TBQfUZB+mBKYcv53m6VUnIQR9NSwr6EiWn6JPS3tYh1qPuIPn3DxXf9zIVi80ICeuxE2loKX3gH+2Zb9X9U9SIil024s2hcFVhcA3wTLqac93OGNOJMdV6tKcwqnaMouhSOfVgUaabDqwjwqeoAWvhhbzmHc7OQ02iI6316baPolnLW1e0x1yNhSrlyLfPpHIFX2eRM8vcWbqwK/HHc+bvG/KdgOx1+Sd0l6o2HNEzp9ZSbhuPOuYHENvE79A7CEw2vOirOKfO4by7CABugeZwL68FcCSjjfvmtnzPbwg9BGBCT0AaIRt6OcQTEe66nPlnllFl33URN6e2LHfJQU85iCRcZULiVZXAG2HERlMHsd6P5dCWkIF1iCPbtU7VZ5xi54Yv35WSA==
