apiVersion: v1
kind: Secret
metadata:
    name: pg-app-credentials
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:SAph,iv:drgyS+DMLl7v7BuDzTX9lxiGtxNXNLJIPA6BeEKl4vU=,tag:WOamVZ+3MZ+HUBY2C68cjg==,type:str]
    password: ENC[AES256_GCM,data:wWcFTf0kisNlqSBkU0hePzWAhFi4KFKhJqsO6Pf0gA==,iv:8tNuOlfXSusq7TAw1n81wh/qGLuPyqlki6jbW5gAeXE=,tag:/PiybKAV8pAoq7l2P/RvYA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhb29nYndDWStEakZjR09y
            NzJmd1FienhUcW9ySU1uMkRWcTJCVWY5ZDBRCjloRlRWWDMwMWZySVp0Y0UvaTFo
            TzBicDd3eGxWL0FYWHJhaC9qaGVjNDAKLS0tIGlkdUorcTdBbkd5WTNKL204TXBV
            Yk9BN0NlMll2MnVzcFo0UXZTb2hsSVkK183HMGdgOm4VMv+ums09sCnQimqFqtCc
            aTdmJEuDalGmpYkN9sRh0Yw1hq6YVmQb5VE9xr6fOjKUYOGA901I3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n3j7p70f0unl5dgrjhtr9jxrdntz2a67dtntu446qus9c3jd3fnsp8z960
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWYlNoMWJLaFVBR04vNzll
            ekNtczhOeXBLVDhGclFMUmo0bDkyTXNBb2lFCndXZzBzUlR3ajdHQlFUWnNGaEYx
            Wkw2b0Q1dGlBYWV0R05KMS93SklGbEUKLS0tIHpzb1N3NlFTSSt1YzVMZ2k4NDl4
            MEhKRnRxZEhpeDVaTkNlMFpKU1RmVEEK/mXnQJNrQGHW6LkwTmN7D+SjQHq9Ff2I
            TRUi6E03qRoBOQs2fxCQeNXaoC2B4DM04+aOvyq3cr/OAGBsZIc8qw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age154tu9q7922xu46x0rkfm5l9x3ulf9u5at5qvxeaqfx9sgtm7cumq75jdwc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-10T13:44:35Z"
    mac: ENC[AES256_GCM,data:kNBKAJGY6ZPe55FSbshf6SS9tXFvK8qZdfq+lb3bPu3rUY2q7D/OYP8wfdEH9ZMK71Q55KtRtbU3kKGyeJd7qVx1s0m1igh94UqISoD5uz/0ytjeTo0eT4Nl1bQrk5pdUCC/bf5B5ZXolCAA9W2TKjjMynd8dfndA3Dalutv/4c=,iv:ZSTCTcCeix9ptSbFQJ9rCkskM9d6xNHGuqEomlU75b8=,tag:4Lofn/3JLQHQNz6mBhwHUA==,type:str]
    version: 3.13.1
