apiVersion: v1
kind: Secret
metadata:
    name: pg-admin-credentials
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:1DVE5+KG,iv:bO/u4h5pyGcFRvRaC9ih3s9Svyt7Y5vVgyoauWVflog=,tag:LEUjK+/2roHMB7sIpnPBHw==,type:str]
    password: ENC[AES256_GCM,data:4JcLss4uTfTYcw==,iv:YcDfEr2SmoMvPfCIrEE7TepyDsJ0BjpRC2Yxg2MvY50=,tag:GBTkK+go0X0/1AH7DasnEg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNkE4aW16Y2xiMFhtWlhB
            KzNCQmh2bmVHMkxmVWRZck5UVmVaYWR0ekRBCkVIRktvNmVzTmZURHRIM3MrMzRG
            NTJ1dU9CdFJjYktxV1k5Y0xKalB4a2cKLS0tIEVTR054WFZFZTVDQmFENklWd3pG
            MTU4YTYwYW1aVUFQYnhsSGpBbjMzQm8Kb14ig5d4tR5qqt0i4105Q1Oz4V9NDP2k
            GTlURypydcueRC0A4/DpnwOWJpqmHRxJYdQ26Yyr2zo9Kdn5M5qqDQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n3j7p70f0unl5dgrjhtr9jxrdntz2a67dtntu446qus9c3jd3fnsp8z960
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNk9tREdFS2hRdVdqR1hQ
            MmZjR1UvZUhQN2tSdlN0MU5SeDRSbmNzdzBVCjYrWFpDSGE3YUxxN2d0UHE0NkJ2
            UmNKQTVIanREellVR1V0WHV6YW03akkKLS0tIHB0cERNdkVXaGJlQkVEdG5OTnVU
            S21kODVPc2F5VTQ5Vkwzc1NJaCtla00KXvVcyqVVGLwpDhZ/ANVx7+KrLM8rEAfL
            QZcXToxsjywCFfr9qhEM3t1RLAtgulBmvITQfrQpgcJmmSqwXo+eaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age154tu9q7922xu46x0rkfm5l9x3ulf9u5at5qvxeaqfx9sgtm7cumq75jdwc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T14:16:36Z"
    mac: ENC[AES256_GCM,data:Gl8h7Vh+H5SbNNQtv7MTboeS0STFm0XZRje5GgQg5JsCBOzLUbnonLRRYTuG7vmAdeovBgd3JI+lqeDRJlGZ1f4oTLS5bpF9GDIRdzq1b5jCgxSSuvkVrQXYxO+Ojw/QqMtjG0RyQAKJ9uLTmA3rRbb7Dld8umFQqB68T9iQdEA=,iv:ITSy98QzSTxeYHYha0qhoZvkhDwQ/+wAwK8zqgcfniE=,tag:EPC/d0Tj7TjCsZfW1tVmUg==,type:str]
    version: 3.13.1
