apiVersion: v1
kind: Secret
metadata:
    name: pg-admin-credentials
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:O7rhwLyctOL6,iv:eiNdSwz4KkB/Zl6Z21UI6XjabWBtr/0/6wFFmIz/qDk=,tag:Q4xCxTBEPdRPKVdEiwztIw==,type:str]
    password: ENC[AES256_GCM,data:zcWzb0aWgCAJlWfRu+14HYC4DZH6lPw9pPTq3qhcUhgyQHE6fi+A0ccO/z27szxjb9xe3i7BfnRl7gpGQ24y8A==,iv:Ze2wPGp8KaYQ/ovAYM118jymR6Ie2RYDNMzQoAkla5M=,tag:ZWxzX9C4OUOlP9wemuR7ng==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMlVUbURNaWNDSnVlVndv
            R2FjUy9HZlpMMGNtM21BYTBPTnczcEZXTWhzCnNRTnBkbnhDVFcyd0VvUnAzZVZF
            a3lqN2VEWG0yb2FXRWJoZkZLR0lJbTQKLS0tIEszM0M1N2ZuNE9tNElwVGthazdF
            eEZkcFNhS1YvQjl0aVBJbXkvSk1YSEkKMzfPVBaY7F7JkzAY/mCAX6dydflnmH/a
            Eo/QFYtOTv5U+LjWquts+4YQR5cnkaBHmcm3DbFf8CqKOACHGMfbPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n3j7p70f0unl5dgrjhtr9jxrdntz2a67dtntu446qus9c3jd3fnsp8z960
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3S2JjU3JZS1pvdjZkMmpY
            S1pMSGp5K25McUtsUUFGZjR4a3RFQmdRa1VNClYzTTR3QzdZKy9oOG1EOE4wVnc1
            UTZuMko1MFF3M2l0Q0I0RUZNTjR5SjgKLS0tIDVueTZrdlp4WnlaelZHK0lZWTZZ
            T2twZkNqTGVoSUgrQ1BVUkJKazE1eW8K3DjFhBbLq6n+kq65vUIq/tIoms1L54Iy
            PgzZTtg+PP9V9s5pcniN/Gv16n3gpwwu+th+oRW82SCN5KNf+dt4tw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age154tu9q7922xu46x0rkfm5l9x3ulf9u5at5qvxeaqfx9sgtm7cumq75jdwc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T11:47:46Z"
    mac: ENC[AES256_GCM,data:oKQo1qIrN0ZBgkL3bJgk7Aya/cFbf81RNMfMaPe7IsD8HYSKP5EUDM9MV+YD/zZe35WZi4AHVewXIBgTj1Y/8cQe1CsBIbCZx7i9qrFAi7xkfKj6/fBIbBohCWaxRz89vTABpc0eLtrtf3Q5434w2gVdfkpRIkrsWFtCAQEsSjY=,iv:jqfazR81KYPjPkpWABcj/5xqnLb3stxOL7T0sd0haa0=,tag:j1/VvytuXgVcg15yRD+aRQ==,type:str]
    version: 3.13.1
