apiVersion: v1
kind: Secret
metadata:
    name: restore-drill-alerting
    namespace: database
type: Opaque
stringData:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:DO006HE93qYgy4j4btw3wVFEBT6bZCrhchIKZVG9jm1oAkltIzF8YMZYljEBPA==,iv:VwHCDL2N4U7Bbost+R1k+LYQVDKgkQi7NJW3/jbffIQ=,tag:pDpGW08YEbUUlcXMNxkPpw==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:UFq+GDdLncRJmWw=,iv:nTwFqNPgPzQagQeoPxQ8sCtmMixRd4/YscS5VNCrFH4=,tag:ehkz+Sy69gX35hYDDBnohQ==,type:str]
    HEALTHCHECKS_URL: ENC[AES256_GCM,data:OM3ifDSc/Q+ufjhdmD+iMwWrtB24jrVxN+nt5Reszq1HJs6bGMZmQBbwzVSmgHiJ/svA2kYTg8w=,iv:C004louwYDFh0BR2ZZDsUjInxUtYjK3H3ZMHLv099JY=,tag:nJLfQswYRo2hHRTf7zCXwQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMEZHdDQxZUNMUFNzakw5
            OGFpTjJBNjlBZStBWXBDVFhjSG1FTlNBdTBFCnUwWlhISjNuNUZHNkMrNlk0N1JV
            Uks5Z0IyN3FkREdwNm1FQ0xmSC9nNDQKLS0tIDBlbnhUZkNPZCtQWHBMUGdSdWt6
            VGJFOTNMbWZOMnBJdmZBT2NZcWlNZVUKlkuJipGo16UFCjcRIMw0hw4PBMmMCl15
            2dOk2YMgITL2B35T46GQ4IUXV55RFi8eBNkw+pW6th4zl4GLo5A+mA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n3j7p70f0unl5dgrjhtr9jxrdntz2a67dtntu446qus9c3jd3fnsp8z960
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWnBQeGhwR3lwdHkyQ0NS
            c2lYWk1CMGF4Ui9DMXFQTkFiQm9LbVZtNmt3CjdJa09CS0JTR1EyUnZrQlZvWGxQ
            czl6aHV6WGNBUzdEZHVzM2N4bVBoQ0kKLS0tIDA3OTE2NHJWRFJwSEF5UzZtdG5S
            cTlPREVENWZiQ3d0emx6UmpPU09DSTgK1wAImxFb0FsBjW86LE7NeaOxoIz5CV1d
            HYTtLlBU20ihzfSCUMvipv07Bc14cKKm/KTTQeXyrhgJ4lngplXxLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age154tu9q7922xu46x0rkfm5l9x3ulf9u5at5qvxeaqfx9sgtm7cumq75jdwc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-06T04:14:16Z"
    mac: ENC[AES256_GCM,data:zRGurdiEzTkAlp7n2S9rPxN0+QyKGpbDfAbSYxkJGX9VKLvXAk64bNEglxdzltWDO6fJK0D60I5cc5xDZ680YcGNLVGZPaHDVN3DPLgQaMlCOF0PMftrS9N6OpE1mUJSkDvnwjoQewA6ysZ3Kf21UEeVmSMFvQiWTqc63wN6qjA=,iv:192ydhRWybIlq/LTZc4edMI6oj3yBE3JfPthZnUNIqk=,tag:xOSozKkvk9jnSXDzOr+YWg==,type:str]
    version: 3.13.1
