---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-example-api-ro
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  encryptedData:
    password: AgAmpmQN3Vu3VJKviZl3/9gjIXaYiXBeAQprUjmJODfanq2WJYR3JTdIcPZtfurdkd2m/ibZ3lH3cYWpPpQrGEit6vgGdVgl6EV/LiTlhkml+TWkkdkG3sUFY2IB0b+RJcHRSWoDsRLu/SXiKG+1Lvx9+JqY/2kRWn7RQwOD/ebZk189iPYuD9gjYVvCsKoyvdXpoexWHEKYIKHSKxS5IsE/qxKam3NECLFiOhnc2HtqihkGbZmZ62z145KeDt/asPEHLVrSg9DiDIgHTpXrUkDMTZLk75DeE7UoIMZeiBI/tOMls6VXXpHm3RM40WWP0r9266CuCuQSxRSAgvNYKQgMBoYy1EUGmthQJKavR6jYgXVSrFeoYz0D6G7OPH7zk20uR03v5APNtGKX6GeSBChY90UJcTpGMEu5JUBTdnUSIjoKOO7Sxz0NJoY4VZbYCjhLqqLkylW0pAt93OBoyazA7YCwarUCm6aeuWw4ErigcNASfq1IsjHZf7Dfs2Hzwq8m6AfgWD3McSdZMQUr+hpMQR6AqIDmGg+iwmyDPGjX7cdyGc14Y+6cRV/fTQEi1j8sDNMWCQ5CEc9yHuI3VgEsm6LSDnN+URJeAvtaMv3y+UG6DVlhkAbdTNdfAYmUQILZQqCjMokypB2KssxkaG+8aNqHv6t19Vr1blr6BXtDgcLDvNrt3I8AywEVYdgM9vDbm/fwzwLoeYR5k8kN1/Fcn1I6llsQs7XSTzTAlI8WHA==
    username: AgA3YO3z1AMoXwLJPDxxUhOnXqhudebZm/KeDt1Gqt5Vj7DlA31TOlUCyOl7Rk13Xwayx2yzXWJ2oGHXO/oM7rRJtYUJaRZtb55h2yxPJPNlDoAnsxEfmEvb4gx3NycuHYTnlxxzd4m/5ThbZnGmMxEnPsyMzRyUwaB4yPpFYRYFa1HK2mk8IXZQ0gT2pPh20i0YLcWlHW5wIX5Ic4J58zyFUlxWqzLXMrrp8ivUWqGwoz+Ce+AiYuPTBh10Bm/1VNikVUhS3TxkDqDhihCJvp7uurrTpXJJbK7cRaQ2ZVLAII+qEsIlkkSt1uoF43LsDse9xm0PLo01XYPSZa8vXEBGzvCkXjAN6sM81QId/j5w8bWNFP8mIG5abK722aO4/KAwWnHeKmuLROokFIxQcUTteW1BR+2+rqYZtlyL0O/XmomfHjCMp8d6C4wInMu7kFW+UFNIH0tm4zUnM77YFmfD/j2ED6IFipT77t7LT+7smYALfh/C8hH9zhl3HckQeB8uFudGPiXN78+TOXr5/y0Pf0J9nrBoL+REfCjBg7/Fgj8CK1YduhQ2EuzYpLvLyjjgdm5z79ZSfxbA9WO2Z0TQ6SAMKLBjSDJqO70wb4M78umwTnX6NtsqlGwSf9gu+qZsGtKy3Tf37mUnCCox5/6QCTlUkPrqzqJwr1XDpQ9BzYCpo4ysU2ax+oFD552x3pjJ8q/PhfPeu5wTltKmQQ==
  template:
    metadata:
      name: db-example-api-ro
      namespace: database
    type: kubernetes.io/basic-auth
