---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-example-api-owner
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  encryptedData:
    password: AgBSJraor8QArTxBHViD9R/UJDk1J1oHfvZJmGPGhbXuOcLyIqO2B7Hjve85QFl0nzT22PCy6KxyevudMqYxAdCe5cr+xDe+dZ2PAsNqzqSoUEbTr9PLIPYbzcUCqoWnWGAnDo+r7mu9ErWEHsoZ5WKOHcUhChLeFekBo1OhTE6zCg24riTxlWrrIUqBFK0QpXRtttjKthg3HDLNuFI5KLR2uy4Sf1v7fUOiBaND+VGRvf30908rIg3Pio3NR7Q47Qq8Bb8/yHNQhVWXgWO5SGFegwaiL4vWhrdyEJNsYnNC6s6Oos5a49j9f+MnVyFy2SxiXaCLAFrDmjR8aUPpRbWebrBzM31ohSk7miVUqiwFL+wO7u189dOpBc9jy4cSne1SEPnbZ2ziQVcd7UdCzosspcNeqjrFzH3DcAaQkNv8kWFXE61dffL/cbuMrT8bOhUYVVTMHDVKMIOGypQARZloGPvTme31CoDOYWF95raT68aoriMqS/0a+DE+wGL3+QGXbCfdkzb5yYITHkL32dpdTLaaLfpC86qxwP8kILQI2aKGdzyD/GO9OZsFToGoUNAjfFRiSK0kzHHJX38M0qF9LJaQM2xQ3HHFAFIecG6siTkUFzEnACM0nZnu8Y08mYX7PkQKWzfQ+lh/BBsVGJVBYVBtetC6eP0yX6ssRqd2CoPSVI24xkCQnqncbQOaZHLQea4YGI+SBv4MTv1wthv4PWIw1IyeXEclA0TWZaQiEw==
    username: AgCHt9wuN7gw3IotZXRCoi0biIbCdc4rC1cB3EV3Q3UzV1iunYayCNdR/fkQNk0re4Wyu54Y615pklyQVR0ItQg/ogxIKdes3on6ZtDccmLkqd6wz5sRFert1OonCpSO3l39cUbkrRje2sFY5E7wPd1q5U4fqF0AhArNX4dG6eBXwNmfy0IlahUnklc+gk00fIZhZWv81Iw8Q56RRyF8xNdByxdPOJ+Ifeu5MZNLcLvDIjrfK6blTEqrfKab9+gBgXVIpfrBepPsBCGnYcjDmm+VRnDSocZ4JkgARo3a/lyXU8C7Tq7zf7jFMeegjUbuFGMYoUcD9xjhaXdh84O6UdDEHS9TRn1X6h6bS44+LlDPc9un5uUmA+F8PwpngbaS+p1Zsc4cWU13iE97wb9pqQ+NCaYOEUjf92MA6rWrlCYXMzsTXgRcNU0PIijQ2rBXz9Sk5QWYj8QM2Le0+VQ2Qv18OmL/G8bPfysG7n/qrc/SOcpZAmV7IVpdXiG5ywnG6L1/a9iDuiMlUSOG0YsZ96/LJkB9M53YWtK2IP0SsoyRkacVfSIqKuBka54rzYDM3F6+DSKALDJv1F8dwZ1gpXQIerhJTdZU3Skl2GcgwzZg+SX/H8JX42EnBP3KJu/iuJ9jvxuryXunWN83sQ8qzORKf5Y3XWx6zjI1aa4laK6POZIn6cPKgKl+Gz+6pfNczRkiq8U9lE+tyvYBvw==
  template:
    metadata:
      name: db-example-api-owner
      namespace: database
    type: kubernetes.io/basic-auth
