---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-mydb-owner
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  encryptedData:
    password: AgAj3++ZC2Yw1mLg1HKEapq5wU3JN7p1FR7gqRts7AUE5y3S8BOnsEmFeYDzLNyQ2BE9dAg5rDJqCmC5bo9qTi5iF6PpkVhaMgCyTvw4biOZLMxdyUrYgi4gM5oI1oTGwqNMK6FxOEifVCvsfMm9boDyDTNNwHCmg0oxFZ7v3S3TmWFoq8a3ZpOzAzNBVdgiyX9Z6dwoaK6lszOLxtA5NNd34tfD7ZbJk1he/hXYRzowwe6Z6K2BH7rWPoMNnzwXdas7QF3iUogeUiaJ9E/EJ6VtQHveAc3cP9kM2yUM54ulYHqeZXlJE3g3DJ8jPKZ4rd1Ha9gHYNHLN9BJ6D63AyLdKJtoqCKylUOiL9d8vDT2YrGyn9tSRcFq7hzm/Lse47Ih6zYY6PVPyAqxcJZS2qPBooeo3CKU/7aO2l163ZoMJODJA16aLFEKP0DpXFyIoqAgmETcvxSju1RJtQ0cBs27JGgba2LXqcskTxaT9DLX6dxkrBNJWnaKw3T9eHLDDqTMomhvuIZw3X76TxTsL2VdX17XsotPrWu7K6j98l/qwu1gWoLnzjKw9Fgow9RyOjW47GMvzDzj395yz2fcBivpZyZSZlIlpf10fT7IT4hYz+uu0GCxE6vGZ0uSt15D6pgrGXfzVRUWqn/O8aMBHsRuH9qqOl9UYhsTeDdhDzVQanFqdS6fbmOfes5mY4bQHhKKDRIVmxadaJ8quJ/zJIvjfgjbZhyBjY06okSfUDD98A==
    username: AgDH3MSRfzeSSh+c5Tl7bK25VSjOekMzqezxdOo3l/paG23CVFpry5M8MsjkpRyoLSX5cAYy5F4i5d3FQI1KgnS2QLLknYVjTy50Rbvfv+IILVFCLXHgDjLz3kbbInvvbmlOwzkduQH0EGXzsppSMjoXTB/RldwFD/kkBZiwqsbobiy0pSBkcfeex3MEi+P1K/MCQ8QXlZPl+SG3OIgarnZzSZa93mupm/FyiB22gSZRMurtYueUqbNX+2/5MSevO39sZgaQiF+kfSreBTvl2DnF8MrLJD6JICzqdJqvHUZwaGzZk1FZ+I8rs81zfw+rhbwSCr4H9Uneww4zhDfEOfKA9EuVjCBLneaSKbhCNwR58PiJXzZhZmeOiYkGQyBKbZrnyni6YMYGSd4yElZU+5lPuHPMAOD2y2XqGIagaGK6lZBGMf2uRMDNPAngWcwz+8Jbz3PX6mE+jdfUgqF6HSGxRDfxc7Sem3NsN0Wt0ruH6HYj9zHd4ODKZsiRN2ez41tNigISqPIVAbVVbormjnpMeV7VRWx2IkK1wTZStJ3YPvYZPQLMHtiTSf532nAto8tnm52FYYrlsOhzNiR5WwXbUhRgeX3DrzHdguZlovoXE6/IIVKpZo7A3xJYoUsGBdwZ4jKUPi43xPlHH+ygeNtdn3sEyUIkE28CCXRQEXVX7z6hEq4o+VuIV1g2wBeO089YojEG
  template:
    metadata:
      name: db-mydb-owner
      namespace: database
    type: kubernetes.io/basic-auth
