---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-page-ro
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  encryptedData:
    password: AgC/YqEiz+jegWvgB/C4CSg+l7O6wdsPxYcWX5yWaDaTOpaEGr0xFrCVKL7n4AD0KA+KnBUy1dTC6dbmHMDKXz/5E7Yuj/bQTb/aNkXMyLyYYweT6LCnLDlcGAMXjfH6k0kWDcr7JUD42EKpxdLuGccgAGPvAW+NCpl4l76kES4r4lmC9sBhxgjFTz8zzdK5ja/oqerE5HFvdXgAAt7WHzvf5cZ7DHXBAYuuVAemx0JeaIFChXZbcdepA0iZzdM9twl+3LCfUEbB/Nz2COBssjpGBApkECkC/D6H3Lac0UPlQMx3EfkFICza73Aqxgnlytoca1ZQW9UvymOh5OZ2Fst8XBzwuF4Z6FuUQ9vlTQ996mM9cS+0E47lH9aNrDYKj9SYKUhf7FrUeQOGb8TsAzXziWj7O7Qq7w74uCROTBc0A08tZY+zmNr7KK0jDqa5YYxRotvcgGpTK1TdP2ZXL+z4p8Vy1whv/sxs/DUgb7WW99qCPDjL4mLFKZ8i9I00oY6mzf+gxRXYJUpJwn8ZgW/pqAuxGn7CkKtgJggCsQekZ12OWRmljY4CSdr01JJBThFpFUm0fxljct0GkGHkbBnSX/L0onYieaW2O+h50kUyg9NT+Hk1HzRjRbnXva4AY8e3UxaJhc/03cXlCaP3YTNFMydFVJZ2ADRSo/IkHxA2JYHmiUqvMnHioEwV7winDfKaSm5QNdjVJ5oOUAfv4YdUOfJEhhOE0dYec9969yJKrQ==
    username: AgDByRjV/UJTa9F2eZIYGSuZRdkDYNWrvqbh8CEuOcxGK6ZJQkPEKkbbYgm39qEHP9uEnsItqXGgKHoTD3S1Bfa64ID4sPrE0KMITxirEsBzfPcunU7G/v5gw6b3nZhGQrfeMe85T1XoZWytw2GGCb62cfTkv4erZQe3VYpE565md9L8JEWGmLJiXXqSWhtRqFFXejkKMk4ndb34N9Mw9wIQwnU2w44DC8zqMMdn5wc63hJDqVK2l+sBOQkAFIbOY3XzUxXGPOLlQHhihm1/CmnldRdZSHmxCWzaZWrqjo2AUpwuIGuCzMFo+AvxjAAR50ZSDEFtSj3AnADFPFs00Ag9bzkWrgWFGkkzpAv8PHKTv/TQSO6meskGfaLuV2IvTbCCw79IBAJjMalQwGeHCEulywr6mxM49XP73UJK4Pmj4NCbXdOJRiXObNTzg5WuuiEJjQvGDmJsijuKFSzu0+82y7sIeNSS5KKp8jYZWfOuHfXa0cZrOBCuEYG7DZ6ukTYBNuZzAHyXA7GiOx7Z2RMUa3jZxIgM2d8F4/nY325oOHgKkGUd5f9QTOzA8xokHzvmpZxc68mqZQ5Tr39qu15bsr+fL2kClhSFzfz4D0/Z3y+BF6FRV/P+u/GX4+v35XO/g0EDVUrBRPokPIeGrz+OzQKCvIhEwy7cBlEV0nXGSVg4pb0XZHkp3GSEGV8vlCM/IjPKrbdR
  template:
    metadata:
      name: db-page-ro
      namespace: database
    type: kubernetes.io/basic-auth
