---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-page-owner
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  encryptedData:
    password: AgCfyeyC4RXc2WMlvE7tNDzqFGZdBZ6puSzWCbGCemhTYxv4p2JvA4sd7nNRGXwB+DP3sL5Pb2tW4gdXvXuAESCAHR9xlofZmsJVLgOQtANVCJ/xhri5d5bblTUKZg70ULXxfJ9NS1fWXad1Bq6KvbPUQCnojeQlBT0DZTWKPViq3ZmCvUIcpo0oSriA1XU9pQ/r4lXjX5K3rTCnCDVQvYpEUau7UKkIVx5oSGs2a9Ne5uSlsCGPp0HzY+KjGmDC3ZQEgaUVoCfy3F/8lcLYsO4egXvbxqxMAhP1uXpWhNgRM6epRFMcx8N7IxLU4Ax1ThQsKj4HRIR+PWilAGD+2NDQjDzKajL2p+iMtTIYInG6X3v804MvoxnYvvDdAqKU8mQmqon5qoaL3k9SgnEuhLAk4oI0R0W4vSRzXfh6MQGMvxpUyEx9xzEMFLsxUo8/df2sqz1dUPAn714cuJut8v7HKP695tJEQCHoZ/QDbt5p9zSxP0bWE3lBYYNx/u5DqyZp8Y1jHrQRhWk0BSYaMuYbZq3gm6SR2k9aesJ/bcAOJe2hZCDalwKN192ghEIi+vAXPlsscdRsZgOA8sb2HgT9O/UQmIkrEgF6QuxZsH/EfbiSoy2lJqHBAmZ3seLiiW7Nr6lESLgKY/dV+9I3tfKo0chWchEOuvwXU0lWCF6IJAqwhSzmAqW8F6RhZ/yJMzbm/puXakl4+DvoZwGdB5ZkkAVCnQRmcev14mrGAFIGrA==
    username: AgBLByR78JPbrEMICiq9XVZQNcVIK1yp80cwzYOgVQmtSj7OBYVZffegaxtMYhWm8ok8Cs1ZFsVccLAS8mEWnlK847JjmjY6CzHDB/N347EzmrQaos0CnSHu2bia1zdkp9QTWeHHAHP+LbuLMPWfiJe1bqHx+D4a4uuOgs7VHPvTr67UJNAQn+eDQXu8Q7jIAx/GNcR6G3t6zTFO89BmwIliYHTSK6rBT1TFwjNIXle4Bt7PVJZtHd9JrAtegrtucfbLeNi4ZT6PIvBjB6yB5iZQnhJM6c7d2ZbLegAOMzmElKB1CSIpIPp2aMkPpcccanDtFTezFV5lNFPr2Rv2yO/qk9ZoGsESkp9UwnV+ATAgL8HRfuGaLlBlN2NpkWZSueRRH3wtuaYxzNtP6XoFpfkBEwfqC/bmk59fIhiECgeodyyb1Q9rNr7QDvjLsytMgfI4fFUVVmiMHL6GAuFGq7iSvwIxOy3EmbXIPBfq7YDHjX9L5L19n0nsmMbOxqpJE4FwQB+jfIfSRp+nnaX/cYVFeWKLc4AS8vUV9giScCzDr4GsOtsdK7C6ray9ePKxs4M35ZvrgolP/pOo1qylOuphHOLzgD3Tn2UTcRQ7QS9GWCirzek7fZBvonBoGf7jKX8Jj7PNt7GQMzrUwDdLieaA70UjBdhSQwhtJOkZqS+4IpLxrXhiZqxM1PxvIM4gpei9WYIn
  template:
    metadata:
      name: db-page-owner
      namespace: database
    type: kubernetes.io/basic-auth
