---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-page-owner
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  encryptedData:
    password: AgA9WX8p56T1GOr7wzEJFaOTV8+8vTav037jaeFp6LmvYLXoSlOMUTCd4ntWBqGf+mZC5K+wk5vl/9URyOn4O1q53szGCioiboizLmoek/TyINciTwMez63+72rNwCfVbLBfntFtH3HDhaQz+bxb6L4LydUugAXfw6xh37f5rUUKKVlhLX8pZ2seQfHLRT62m74DInadjaKFmy0X1dtPl9IQ4hoLKyMcgrIrOH/sSALYNwsRFir696FJ8f4U1wHacvjw/PFX1/P7FNyybWPw5u/CfgONLP55rGHJjN7y1tpS8gJzrZEp4eM3KrQ2fhsbqrb/PbmFyXdr8U3kmnuPv7BD8wKWlRs/mkyUPbABWb+bojTb3h3pq4a6kwEQFOUs6FuyD6awqCfmhi7bC0va8HJdA1kRd3b2ir2tknxranA8eApbDO7uIQmYP/wHhJkBeTjyaFM6HiKvsFUpLzzD2e/7t+yGxDCqdmxElw8c+OoXWFvdHC0iSzUJ0uhfujctfZw1EvaDjJljYaMWwbpNUI4J94mCcOBW/PBIihNIwkP+huX+xg+PAa1tZd3IsOpc9wGuXZd8JmHpdAuCiwUxfIOIQvuhx3Rhrhndgj39ZI6RE1kUdLl4GtylWsE7nG3eiJeQjI8e1ntPqTrWt+FCLM7X8KIdETb2w74vFv6x7zcQ8kBr8eLEuCRYtQRYUJlXLwsDdYM59KjVfvdF/xBTlsSkAziztZe4JjvmwjLzvefViQ==
    username: AgCsfA732OXNy8AXGbtR25tcoMQjCAreyYrQRAbP8eI7jFMwiwv0s2i/nrco2LLGMHvjwoOy9sKITNVH99No6qedEp4bX1xkS0xtYUmCJDa+ft3CjaQD9qBMJm/dUI/Ua2gRDdCnx5QJ7wHf396C4PcN03blDWDmdfsp9lIW/NydtzEMtdJI6TXW4JWtVXJgt5kvUXSL3W0dKj02x6FGVE5cerLzl92uY7AzCj0R1SXdyyLx44K4N45ZW6ElhU09JdjzYxoJ5HhrV5jXAODJjZ9ECfua7fw0u5uIb9AwXdEkyiUgslgnMycNztcpQGTtszbcInX3+6rlbMM0cqlh1zFaKzJvodeqlB6Fwf8NsgSlB14xtVGrNq45z05GpXp4GFhvhg6cGdT1tQJCFCGOxQ8F4tx1McqsnygdJUmjcCPQU5J7cmRaGQ5wLK2oUdNfuLCWZc99zSJMMHuWwYDCPag/AGVvRZ7GmK2XfuDejKz/pmUGKzdATqyn5K1ZUezveOnItkASHKEg3O7/fzVD1COejd8JRUMxTlzfbqB5MshEelXDCZFOl3sESUCanBjk/CLrlhbOvauLYTzY+5va4Qugs3zqKlbTkX495MPL6Q4bIK6mwjhyd8/6i4Vn36t7vbJxj3mp2eE7UcFisIpqZON0uxB0r7Z1ljblEGuNGTcpQJra/mLOBjI9yuV9OLtH3G7WohLD
  template:
    metadata:
      name: db-page-owner
      namespace: database
    type: kubernetes.io/basic-auth
