---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-page-ro
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  encryptedData:
    password: AgAN8UkgebWXLu25topDBWGjjnrno8LmTwhDLR8akY2tp3wFATl6X8S/1NvaNtKjIkZlmzjM+5M85Tc8351sOBKYOkJj+yXlzGIrIyNm7xFmr5OfT65jEn5jQWWj1UukH8kOABu7zfxr74a1ijScguiZKwAsnXP5yeGF7VNcrTWDk1ZKpJOni9ldJCwfGRMnIE0vIvjLPg+SAvWPzNiE6isSCIilcCXGT+U+lYianGKRBFpLIkcQDoOl49XOGvxF7lKbQGKX1F+l+6ptEwuZWcdmuUCEEM49aFW2DUpT623oleZZZxEwm7M55Kri1dXpmknZ8IuQvLnoh6KlAA4iKnX//Je82mor+twI4ooI/b+SDvUbHVu+o0895xUVgBplX4hEHzgjGWFo0EyX3QfcRG/wXi1tRjWTDMBp8a5+vIgvGJr+dg1yz4kKksrFheD/xH4MhgAy7pE9LPMxqHUHR8ct6CS04hCck43o5SS9Tzlw6DMxqJDFGpWwS7IBSqgHbDnv1B4RhJNqtVHcipUoytedzac6oDnvs9Wt9Q2O9PCb10Yjt17oh/sm0Bu20/lAGt/v81R9QJukk0KwRpajbFzBzIql+eRUSvhH8oVp/6PnQ5mKmbCyp8yIPOSpPy8ayy2eR2NSE0Je7kbM0RnyJDlrxNHD1PB0nkdzMBVqXdXRelIg0Vn+d3Khjv6HGVsi1Kd4N/4LxJG9+VE68S51dfQ28axO6yxYvTRIgFCCCBEDBg==
    username: AgBvgk+mcIYdxQFYwfxdXSoME6ok0M95BwPUcTvVO869lrd6as30yFenbMOg2+DL20Z462jJwhe5M+c/vf7gZHjC37ND9dSUnxVEbZKnE0I7pfHIc/wqbpkb5z4H4m4jheT6j+sc3kaTCYLGQgojSiaFE6+6xDIr/SpvXig6YFzXcyshzO1rOb+GQYeFogPs5bRLzMWSWwleuhGc6Z3M8ZWWAzTLWEbX3qtUSh1mclnP2UL8WKM8IJbsr+vdEFKzcb4KIc4aeTpZrtnbGoROCRZSwswdwHipTOui3SHHk/iuD48uRdKf2n1msSBFw3HMTGZk1v8+8676/+Cw4eSMZaXCE4NoOUAPqngoicwJDP4xT+R71kAYyddJ5mcuxONmVEljasuvw0ojKwo1Hct40DPufMlBfoxq06nRbrj/Ko4X240NZ9bKaTvGBsSx8HHPnEon4mZsxGaZHNMQiGuJ9zfG5TBQ+eBySW6wMk8IxwsbMhFm0w0C8OC+4T1j4JIiS2HdGcjCsCgu95LVZqRlyg46jlLEAPMJbNvN+j2CyTnOu0RaheMCmRkBA4uWTm0y6NhXV8soxganX8tEFgb7e4tMzeurJkrA+ixjZIOIBKrAk+A0G6Ph0dMuXG9G1GxZLrKxO5G5vgeJ8iNc+t/L0SlUl8esK4dF+73biyRdhqaYu2kqKcnevGlnatTUIOZWavoyLCRIVjUY
  template:
    metadata:
      name: db-page-ro
      namespace: database
    type: kubernetes.io/basic-auth
