---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aiops-observation-auth
  namespace: observability
spec:
  encryptedData:
    token: AgCIrveLFz+/iEXuKFzzDDYMqq2LZJnvnxQPCcW70v+ucCF7GXhxNlZn1uPdyF6yqFwZWvcqFN4w0yV5xc1waZIqOQmnR52J/3jIEKy5ZzpPF1/fOZ+2lPO+MKpxLqyrD0179WSMouR2yDTO+fLFIqdeZdAmEpbmBV/3zF3oVLAg90Mh/aQTWejtizoMspMape1wr3hB+qNrA0xtxRrwZ2lcfd2oUFf+2Ij68J7xWZQsaVuTcRVEscYG1MnkZKVUU0a5mbnaMIbk356TFdBPjodMaxzM9Z8286SgFHT6SGHDNHxswhOUFpppT7nXuZu6S7/TsUgc5mFEEpUlC4pMpNx5GpMsPJm4sqSQ8ShVqOsqEAvBfAxt7lwg7ys41ksKLmyjqi5NdWcuSMeO0BKsu6j5Z8z3+U3LmTE9tdRHEQ+GfMbsKLDaKwnpQaA+ZUx5l4p/jxehamGYseB0gpSCCv0E2g9XLHny0qPMrFvEoBHRi5V4NSOMdmSdmaTGS08Yw3j2WQ2NOqMHwYPO/CpGw9+/OgAsa6gpQmx0pdjfEbP9Mn+xSBRQAMjo/gJTlfaSmzvyiELGW89D26JKeW0unNq3kYsX1Lja4Q2QDv27LMIXMTmluEijqBceAjNz/KuXElLHZFkUDO5WqK7nehUx51Fd1JigJHAa6xU/iqT7nnDDyJg4W8fCdNV12DdujtfA/LGJ5p22CvfyhQuJTZyjeODzIFD0ZqgEzk24RvpH9hlZzOX4QJ3ytrpam72MzXhXhuCucia4KzL7IbIRIR91u4sc
