apiVersion: v1
kind: Secret
metadata:
    name: alerting-secrets
    namespace: observability
type: Opaque
stringData:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:iqEZ+H1j/xLQlxgxxvq5EHhgmD0XEcZ6KoedffGBI6b5q1O2yr5nZW6HQJOPbQ==,iv:brNyGFwURchGAIrAP3lvkqRRa9hZFyhyaKsdUWNtqK4=,tag:WoVOpZce3fXv8mo+8quWjw==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:F0suC4EH81Aijfg=,iv:yrqTSEBXrjJCpWaqJN6nhg6uvtQT1qP0fNlwa0OpsrY=,tag:h2z5VFSJvvuQwpMfiRXWGQ==,type:str]
    HEALTHCHECKS_URL: ENC[AES256_GCM,data:6W1m9l/X6ueSc8aVqElFwlJf8s40VdrFVRO1QNpQ2BARDtYEHBF9RbZFNK4i+98bj+Py6DHCFE0=,iv:Gs8qNupfdAi36LEtFMm8s+IunZsynC9+7qgDTMDBrpM=,tag:8qt1Mz0Sc2XaGIf/+89zpQ==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:Eztm36XUiS+2og==,iv:10HZHdOhKOuCbQBkEt4EDz464pX+ROMaXVdF8IT30XM=,tag:v1COHbEAzcxehRjzH2WCkQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVFJEQ1RXMlpGN3o0SXFD
            SVJObThqSFh2ZVJDcEQrTmsxQWFlWTE4c0FNClB2aHozTGhnUlhvWUgxUnVlRjFV
            UWdMWFFaZzhicUgrOXJRTFVGVWFNcDgKLS0tIExhOHlScVRTWi9HaTlETjd2RXFK
            ZCs4bTNFYk05eFJaU3JCUmZVMEhvZlUKFUhFDN5T5Z9yn/Bznet2XvRwILzpz2rW
            r0BAqAD2TdM53mMtbs7lXn6CbrPfeZlZfTGwO0YEM6nZUG5y2uZS/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n3j7p70f0unl5dgrjhtr9jxrdntz2a67dtntu446qus9c3jd3fnsp8z960
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaVd1LzBWQ3hURUxyQ2ZY
            NVlzN1hhays5cWVGSVFnb3IxRURVTS9VQ1NRClJCelQvcmtEK3pMUHFUMW8rSXZM
            RjdnMktBSlpBWkxiakdaa0szQ1l1OXMKLS0tIDNXeVFNMVlGdll3TTJzS0tUWFBx
            R01mMWxPRk5HTnkxaEhXQnRJZDFZVDQKDHYWLCuHfaJ/gK7vuIcc0jBsZIrXlOqm
            /vMT776h90av/gC2ZSALYu5v5ivsRrBe9a/I01tVm8QIUDHguxWviw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age154tu9q7922xu46x0rkfm5l9x3ulf9u5at5qvxeaqfx9sgtm7cumq75jdwc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T13:34:11Z"
    mac: ENC[AES256_GCM,data:xn9hDjG9lNO47PBPTDGi6EE48ETqHQ6LlYSUc5X4HV0qGPNj5OvpwWv3y/O51NLZW1eelIwdPAsjJZEmPMzJjUd5v/AoByLrPTDvEvmmUvYD5ggC85SKktSQfXn6FPI2vVPg+pZEsGL0cH+oj5MyN8i78d47fydrgXis4OFxV3U=,iv:gDdVIHJnXnAnp65de+HXgOLog/CGG/IxmUe7Fi9Euao=,tag:/AfFG3kukpOqYpYacTDmFQ==,type:str]
    version: 3.13.1
