---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-read
  namespace: observability
spec:
  encryptedData:
    .dockerconfigjson: AgBEbueO28r+j7JYY0+OHMmcYzWIg8XfWRnuVqkiN1mIL0jwEVfxIQLDLzEIsINjr+SAiDHRv5uUquiPES5+hW8jIZShI2lPpSe0NAesOB4fV+UbjMlbAgfMhrTzZ0aCvj5hZ1zchzuWC+A9foBEFtTtglhqzDEAsDulio4zyOZVXDN7XeaGHkFV1z7GiMBTDu6O8ANlKV7duchiyiowanVfF38LiSEYczKGS19sFSt/XmYQNvivRzl1GKTkDTAi5Av9E6ddcO5Dxwewq/E3+Su32he+2PLSCO7ajdtCXdmW1gkJnRIVyBnuQmcXak3KAYIn8h9F1pWAwFR9P0TZ2eq3FoYpmYcHot3q1Na2u1Rd5jT8lJoC44E7iJdOLjCAaz9sbNGO7zK3rWuJkh6uXzqFEmRdn0IMQLRDe7f2zHAOlvWatEZMPTB4dITngn4aaA3PeIq5m7wS2fcHt0/mRXe1JLd5Js0cBCZEYPHP6rkqo2zLXyLqnWvu8oulw6EfmvSUsFtVAHhptVfDqgu7T5CfRLZMe/YLsbsLqHHiX6Ozi5QbPaETMHfiGKKAPjVAnneY+00NSu8ZDXF001+eHtS2m8H3aUMAFj+r/BlrtLumvQhJZvO50IjwZFjUbNpnTMkpMqBQ0jGh4sFB7knnti0cGa2xslZKCrhQw2CMSZmMZQcyisLnlmyPvB9Eb9sfrBwalkX34WKydJTlL2nFqxflwD8VBp3m5VEgIZDmKoo+0PSk0I6wkjOYW3I9QGnUeuGDDl3lAA43Yp13OAISDDEvq3LFO66EjKFLL9scX7vywoLrdugGlQ68cegFfI9yCjPbeRmlxjIh+SSVMe4vOd0ost2eJLgFQ4yFKvcPja2hw6ojWRN72dwASrQU3rXcNuUH7DOsVPmQw4uR2/91yvvIPQsXXVcgWjKSzRY=
  template:
    metadata:
      name: ghcr-read
      namespace: observability
    type: kubernetes.io/dockerconfigjson
