apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: tailscale-operator
name: tailscale-operator
repo: https://pkgs.tailscale.com/helmcharts
version: 1.78.1 # PINNED
releaseName: tailscale-operator
namespace: edge
valuesFile: values-tailscale.yaml
