apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:5OKaSYMYX/ikOG94+WMkssM=,iv:hoURkCkZHQYQMA2P4Oko2cNMjGO02YHQm6/prO1NXkE=,tag:GEfquKFP0yV8/Won9ydBCQ==,type:str]
    client_secret: ENC[AES256_GCM,data:z+VjeVwn3ovp9pQFE6WDgVywMrnj+MkKd5O/m+7PRid9u0o/vQet/YWOAl7PugtJkY12lP2WqPXda/C5kUbAtg==,iv:3JQ33ntVi8Lnepj8KZAvoiXkf21XzHFYa1fEEC/isVY=,tag:OYfbolTBQkaktQWpgHPiPw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eVpiQlEwcUhsL2p1Y0RV
            disvNk1tY1NpSXQ3NCtNUGtTYTNNUUxRRENBClBCejV4MTVoTmdBbGZ5cGQyamdE
            REZITXEzT1B0NXVSaW03cU1razc1OTQKLS0tIDE5Q0tjeVdrZEtEejM1ZDhkOXRz
            WmJRKytSbVhLZERZZFk1anVZTzQwUEEKcwXcH50uy/FHideha7ekf/QT8OzPmVkL
            zeV2sYjYyiVSGYpXVacM6GRnPACONZ2W+Mo0p1hnJ418TFapwc6xSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n3j7p70f0unl5dgrjhtr9jxrdntz2a67dtntu446qus9c3jd3fnsp8z960
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1bjBHM1kzaWk4TVQ2d0Zu
            RXp4bis2cm1FNHpCZTJPKzk4Zlg4WXUwTUJzCkpzUkRaYWkvUm9rdlN3QVR6clkr
            RExXRTRFdWRKc2lPMzVHUzFQMVUyVFUKLS0tIDVYSWllYTFhQUt5c29ZTFo2UGNw
            OS83MzNVbWFhWVJka1FPZlVjNGVOVjQKHPFRVmTfnEswb3oOsyCmU04R+K0Ybw6F
            soJy1CZurFP6WqnnvC1OrOaWvVaD/USEP7Qdon0XJGTvG4kjsisUGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age154tu9q7922xu46x0rkfm5l9x3ulf9u5at5qvxeaqfx9sgtm7cumq75jdwc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-22T11:41:54Z"
    mac: ENC[AES256_GCM,data:Uk9A6gzwILJuVeWRGTlTQv7joZ232giG4BqrhxBH/DwvExoX4t4lWZkqSVBuH2KyioAlgkXiwYYqOn3hW6wnkmcgompaoG+SO+MM7aNpAhflDWhIx6CC204bUXGjDB4tB7KCKnNsGE7zZ4WwvcvsEVHssP47Ewi4jpJYqR/sBVA=,iv:wDuhLUZGmw5lUwFu4yq2KDHf4IS7nwrEZXF5jh7hpEQ=,tag:29VY3zb+cDAwkUGA+4YTgQ==,type:str]
    version: 3.13.1
