apiVersion: v1
kind: Secret
metadata:
    name: api-secrets
    namespace: prod
type: Opaque
stringData:
    APP_SECRETS_PLACEHOLDER: ENC[AES256_GCM,data:2KSNlvdy+7VmLh2V,iv:7vklmRe35UVjXcVzQTdSBHf6exZCiNPlEiCqtP2QU0Y=,tag:KBrix7UgIR3Fc99j/aHHWw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdmJlSkJXUHNQWFdJU2ZL
            RWFmR1NOQVkvL3FIejBxNnYwNW1CeFNva20wCnpKVXNla1dlejBETDNTaHEyRG54
            WlRXNGtGWitrVGJxTHZ0N2NiQlp4dUkKLS0tIHgrQ3Vzdm5LZVlHY09UMmlKQ0t4
            K0dZSDVzRlZJUHA5eStySmJ4MHBDMGsKnSITrMGqAkw1J28yxgn39lHdRzsh4Bbl
            btAm3SW11HE9CZANj+Q8Q9M/7BNGJAFry8hc7XgacW9o7vb0mLWd6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n3j7p70f0unl5dgrjhtr9jxrdntz2a67dtntu446qus9c3jd3fnsp8z960
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSU5WQTdTSklZUGowbktF
            dlAyWmN3UG9Xb3hzeEhxRWZxSklvVElCZkUwCnBpcDBMbVVya0phNVN5SFNXQTBN
            ZHlXbTZWR3BSdXF5WERDOHJvdnJWVmsKLS0tIHlBdXJLYU5rckExa2NuemR3VDBC
            U3VGcXQ5TjNaS3pzZmFNbTVyblFzaVUKo55j3r4p3X+kC6Jf0guEJAaeRXYMt34R
            DwXxOkjOnBCcW3Vbsfx+BAtfq4SdOnKUFdB/S5Dh3caOe0ekj8WzvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age154tu9q7922xu46x0rkfm5l9x3ulf9u5at5qvxeaqfx9sgtm7cumq75jdwc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-10T16:50:36Z"
    mac: ENC[AES256_GCM,data:/zsBHQ8EntkLkuWOQc8CqEJZvxzzCEp7effLaWRInvjro36Dtz3vDkeatqIVriLPRoZc/1qiPsVfG96kt89T6p72Q8clPJ1Jf+b2cnm/FBoWmmqtwNBOFlXBmYZedXPpr+RW6vsjT8Xy7ML4JV3XV8TYBrVpXJ6Sl93TRxa3Zq8=,iv:xunCcxoYxH8MpXWK9YZu+HvCwQakFcx61i6wzmdSO8E=,tag:iphYrHh2KEyy+ETYWVReJA==,type:str]
    version: 3.13.1
