apiVersion: v1
kind: Secret
metadata:
    name: api-secrets
    namespace: prod
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:dBuq/J/LjaxcbhHb71NS4NtWHSMxzIi3mPeh/VbE01OjyJQfTQJHHvZ13Ex8XYZ0yOTTKVsgoA2sYjvE6w8ZatLg9BYuWyDoA+462wY6XNaCmxQpRjOREh52kzLf0PEGtg==,iv:CmG7IHip4LWmjFgN6ZxP/Nz9mgTSC31cAI9SD8I5mrM=,tag:p5oH65hxlfY4xjZXai8h5g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSVY4dEF1Q0hzN1lwdDFF
            dmlaZG1peUwwRFZVQTBESEZXeDYvWTcyMlJJCjJ4a3FKby9tdVRDL1lYR2ZCS085
            VkhWSUR0c2pPeHYxeHpxMzNkanoxeFkKLS0tIE1hRm95TXJBdzFmRlYwc2Z1MzB2
            ZWZhWm0yaVJ2V2kwbENvdHNLcS9vcm8KaEvNvM71cCFqmD62bUuz+Gqbe9hsy2hI
            QzxwGyt4shcTLlaExWArEowccPftYO3IDHRftT4VCWzrgL4kdxIuCQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n3j7p70f0unl5dgrjhtr9jxrdntz2a67dtntu446qus9c3jd3fnsp8z960
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aEgrbElmM0t0Y1RpQnVy
            OFMvVGY5T3poS2FRYTZZOTVlMk84SFBPcEJFCk9PcDJlb0prRmswZ3BibDJwTVVY
            YXF1SHFCbDlsZlZZaW5HTzJwRWtQcTAKLS0tIFluWkpBQ0RoZklxaTRvaWl0RTc5
            VHZYWXNkd0JxcUNoa3ZPNVYvMXI2NzgKKa2oQGGZEjIdyEPLhkYdDqzRGBSrr0IU
            JMamLNZ1ybY6o+LaeMOcR2rkiSoWh2DXho06RknBpV7RU85GKI6RPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age154tu9q7922xu46x0rkfm5l9x3ulf9u5at5qvxeaqfx9sgtm7cumq75jdwc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T01:30:49Z"
    mac: ENC[AES256_GCM,data:f5KffZP4yj8NbojL+iKnt8KoLuqT/O2ljblg4BTiWIeyZw8VtQCCwjTlJxEkQzDrvbvuI6a1GXoBSaQMFWvg6+0IkYRnnEiXdJnpQS1+iO7su+Ab5K5iHO6x7+IdeJ13SvuJ9YUFQNCZq6/3rOgTUUphWmIeCrYtEkt4adUq+9I=,iv:RZ/Szs5fTueOxpR0NlNgrQEUEmFnXRj2XkuAIapEYc0=,tag:5gHqNarkLgR39JbQJEdS6g==,type:str]
    version: 3.13.1
