apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: api-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - api-secrets.enc.yaml # -> Secret 'api-secrets' 생성 (ns prod)
