apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: worker-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - worker-secrets.enc.yaml # -> Secret 'worker-secrets' (ns prod)
