apiVersion: v1
kind: Secret
metadata:
    name: worker-secrets
    namespace: prod
type: Opaque
stringData:
    APP_SECRETS_PLACEHOLDER: ENC[AES256_GCM,data:/9XQ9QwPEwWlDmaz,iv:+90L5f0uhwK9e8DqarNEZxswMB5y+DPDax4fudIcZ48=,tag:siclgNcn4i24qoWpDzZrWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMnZVRHhOdEVPK005VVFU
            b2dpSnZQR3hOb2x2SVo4a0VIalVZMFRRblhvCjBtTzRvSUNhUGZWbDZqYWpSU2pU
            V2pQdHFvM3R6ZEVkTFpKSmJVaGdyWWMKLS0tIFJwQnFzYVp0cVR4R2pmMjdjZlQ0
            NlNZRFZJZjFsbCtzMHpUMzBScXNWbmsKviXnDlH5+v3RBQpwmDsLJuuxWLbjMBHJ
            BWkFg44vewfoDZGHUUcZu7ooQFC+jb78v3QwVMCLXR6wIVNPOQ+ZAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n3j7p70f0unl5dgrjhtr9jxrdntz2a67dtntu446qus9c3jd3fnsp8z960
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdHFjUWRGUEZYOFcvTnNK
            ZGFwSXJRQ2FWL1JNTlUwWFVVUXN5b2Vpa1gwCmNXUG5UQldxSStUU0U4QWdWQjly
            ZkJ4YzExZzNYUWQxY2l4VFgvZFRkU00KLS0tIEhrMi9maGlLdXM5OW8wS2dBRmNT
            MDlVclhhSE0zRER0R0IrMWdyMm9EbEEK8wEkbAqj/Qt3HLd41DMM3otyuNknYHYX
            N8mz/sVZ46GXi2MBQEyx4u0B/QtxQk1pnWSYf/l9N9yAOtpDdmACCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age154tu9q7922xu46x0rkfm5l9x3ulf9u5at5qvxeaqfx9sgtm7cumq75jdwc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-10T16:50:36Z"
    mac: ENC[AES256_GCM,data:b+ObA7P/dAfczyMEp/pBzVlDyjCkj/KEeqaJ7zyN8F2T0tCCE6umUN+eCoXzpQhvw7w1PIyvN3QzS2L/8nJcA6GgJRHn3RlARqQzKpxy/VzsspFRtMPeirrIHbbWSn29lxmw/qmQ2qdEIOZoW/hOefkYMDXFWRqa7BknG0fb+lU=,iv:6cYUye8OTvC+2kqc2gbwtPoZXHOfnE4M3m7lhE4CDKU=,tag:UYZZYBvJVwGW4kuIpYhvmw==,type:str]
    version: 3.13.1
