apiVersion: v1
kind: ConfigMap
metadata: { name: grafana-datasources }
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: VictoriaMetrics
        uid: VictoriaMetrics
        type: prometheus
        access: proxy
        url: http://vmsingle:8428
        isDefault: true
        jsonData: { httpMethod: POST, timeInterval: 30s }
      - name: VictoriaLogs
        uid: VictoriaLogs
        type: victoriametrics-logs-datasource
        access: proxy
        url: http://victorialogs:9428
---
apiVersion: v1
kind: ConfigMap
metadata: { name: grafana-dashboard-providers }
data:
  providers.yaml: |
    apiVersion: 1
    providers:
      - name: git
        orgId: 1
        folder: Homelab
        type: file
        disableDeletion: true
        updateIntervalSeconds: 30
        options: { path: /var/lib/grafana/dashboards }
