apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - namespace.yaml
  - node-exporter.yaml
  - kube-state-metrics.yaml
  - vmsingle.yaml
  - vmagent-scrape-config.yaml
  - vmagent.yaml
  - victorialogs.yaml
  - vector.yaml
