apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    app.kubernetes.io/part-of: victoria-stack
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
