---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: example-api-secrets
  namespace: prod
spec:
  encryptedData:
    ENV_TEST: AgBqffOqkLJhyH00MNxtvLk/CpetXzSQbKeXHcCt1lUnYj137cQ9ysCBKJFPvTGn5K8ol5pV/U5fGDj7AiFbYr4l3Eikny8vZHpO752qBMNDtcL6+d1RMEfEtdMc69TdUE9LazP5myny4MV4qKNKdmliK+eKdFDddVVMJPp9/tHaps2fd4X1hiDcVhZaP/5KAThFXbaNyQ8RYk7H+mMQVV6i+9VRs9WxWDDxCaw9ONY4/JIjwdy2hHiDNF4AfIpabVUv2dKI/zUoR1GA7h+Hzmug4ZbsKPbpbYZ8Di+qcQdbmsyiPesvFQwFzWMjBI7Fia5EllBHV/3c83MVgDQvosdaDMy3vQ2xnH3HhfGvX2CpWZuMe156EfGPPdrr2bERL+yGikdTsggjAnW5Ede+F2lTNNG2ftgr8UuGdibDSqN2lUhY0lFQhbS6nfUB2lILYx6MBDb6LVQ9a79bZTdFzrvqabPd5rSDuXvG0OGfMrd/8LJpSjdA3nX67y05lXYT4Ln/SAiDZZulYqKAmxBCnzmSfNYxuOa3LK4L/N6caw77ErwLU3k8xufgI4B1gwlRBW7pFh2YkYQlNnhjPLjkN5kUF93hq7cW/O4eN9Q9bookc1caRphOtw2KOL2t/yxq1lArTDECqV5v5fTemAVtnd+MbOrCprmalCdKnU9gSh//lhqE0p/QaMENVdfNi7UEqyfVK9gtWQ==
  template:
    metadata:
      name: example-api-secrets
      namespace: prod
    type: Opaque
