image:
  repo: ghcr.io/ukyi-app/example-api
  tag: sha-8d6cb151228b329fb301f622ff5d33dc8a3eaa9b
  digest: sha256:5382eb084f83fa8f1520a335f483679a868c4fdc89b1cb2678dad4793b914b9a
kind: web
replicas: 1
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi
route:
  host: example-api.ukyi.app
  paths:
    - /
  public: true
envFrom:
  - secretRef:
      name: example-api-secrets
podAnnotations:
  checksum/secrets: 0a7f652ff7ee884b
