image:
  repo: ghcr.io/ukyi-app/example-api
  tag: sha-0cfec9ef23e87598150e8e42b10146086705158d
  digest: sha256:da0bb0be62668f562ea23db2884a6a36006c8ab7696f6a9194088eeaa5af5710
kind: service
replicas: 1
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi
route:
  host: example-api.ukyi.app
  paths:
    - /
  public: true
